# nixpacks.toml
name = "xzx-obfuscator"

[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = ["cd web && npm ci"]

[phases.build]
cmds = ["cd web && npm run build"]

[start]
cmd = "cd web && npm run start"
