# nixpacks.toml
name = "xzx-obfuscator"

[phases.setup]
nixPkgs = ["nodejs-18_x"]  # Use Node.js 18 specifically

[phases.install]
cmds = ["cd web && npm ci --no-audit --no-fund"]

[phases.build]
cmds = ["cd web && npm run build"]

[start]
cmd = "cd web && npm run start"
