# nixpacks.toml
name = "xzx-obfuscator"

[phases.setup]
nixPkgs = ["nodejs-18_x", "nodePackages.npm"]

[phases.install]
cmds = [
  "cd web && npm install"
]

[phases.build]
cmds = [
  "cd web && npm run build"
]
