[build]
builder = "NIXPACKS"
buildCommand = "cd web && npm install && npm run build"

[deploy]
startCommand = "cd web && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
